[package]
name = "ipnetwork"
version = "0.1.1"
authors = ["Abhishek Chanda <abhishe.becsk@gmail.com>"]
description = "A library to work with IP CIDRs in Rust, heavily WIP"
license = "Apache-2.0"
repository = "https://github.com/achanda/ipnetwork"
