[package]
name = "ipnetwork"
version = "0.8.0"
authors = ["Abhishek Chanda <abhishek.becs@gmail.com>", "Linus Färnstrand <faern@faern.net>"]
description = "A library to work with IP CIDRs in Rust, heavily WIP"
license = "Apache-2.0"
repository = "https://github.com/achanda/ipnetwork"

[dependencies]
clippy = {version = "0.0.37", optional = true}

[features]
default = []
dev = ["clippy"]
